axelera-model-format: 1.0.0

name: superpoint-onnx

description: >
  SuperPoint self-supervised keypoint detector and descriptor extractor.
  Input: 480x640 grayscale image.
  ONNX backbone compiled on Axelera Metis; NMS + keypoint extraction runs on host CPU.

pipeline:
  - superpoint:
      model_name: superpoint-onnx
      input:
        type: image
      preprocess:
        - resize:
            height: ${{input_height}}
            width: ${{input_width}}
        - convert-color:
            format: RGB2GRAY
        - torch-totensor:
      postprocess:
        - superpoint_decoder:
            nms_radius: 4
            detection_threshold: 0.005
            remove_borders: 4
            max_num_keypoints: 1000

models:
  superpoint-onnx:
    class: SuperPointONNXModel
    class_path: $AXELERA_FRAMEWORK/ax_models/custom/superpoint/superpoint_model.py
    weight_path: /home/name/Documents/Vydar/SuperPoint/weights/superpoint.onnx # This path should be changed according to your local setup
    task_category: KeypointDetection
    input_tensor_layout: NCHW
    input_tensor_shape: [1, 1, 480, 640]
    input_color_format: GRAY
    dataset: CalibDataset
    extra_kwargs:
      max_compiler_cores: 4
      aipu_cores: 4
      compilation_config:
        tiling_depth: 6

datasets:
  CalibDataset:
    class: DataAdapter
    repr_imgs_dir_path: $AXELERA_FRAMEWORK/data/coco2017_repr400
    repr_imgs_dataloader_color_format: RGB

operators:
  superpoint_decoder:
    class: SuperPointDecoder
    class_path: $AXELERA_FRAMEWORK/ax_models/custom/superpoint/superpoint_decoder.py
